name: PolynomialTranslatorBuild

on:
  push

jobs:
  windows-build:
    runs-on: windows-2019
    steps:
        - uses: actions/checkout@v2
        - run: |
            mkdir build
            cmake -Bbuild -G "Visual Studio 17 2022"       
            cmake --build build
            .\build\bin\test_polynomial_translator.exe
    
  linux-build:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
        - run: |
            mkdir build
            cmake -Bbuild -G "Unix Makefiles"       
            cmake --build build
            ./build/bin/test_polynomial_translator
